export enum CommunicationItemType {
  INCOMING_SMS = 'INCOMING_SMS',
  OUTGOING_SMS = 'OUTGOING_SMS',
  PRIVATE_NOTES = 'PRIVATE_NOTES',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE',
  INCOMING_EMAIL = 'INCOMING_EMAIL',
  OUTGOING_EMAIL = 'OUTGOING_EMAIL',
}
