export enum EventType {
  CONTACT_EXTERNAL_ID_CHANGED = 'CONTACT_EXTERNAL_ID_CHANGED',
  NEW_CONTACT_CREATED = 'NEW_CONTACT_CREATED',
  CONTACT_OWNER_CHANGED = 'CONTACT_OWNER_CHANGED',
  CONTACT_ASSIGNEE_CHANGED = 'CONTACT_ASSIGNEE_CHANGED',
}
